### ISSUE TITLE
用户名字，题目难度等文字有一圈白色描边

### ISSUE THREAD

**Issue by yiming564** [Ikaleio/argon-luogu#36]
![image](https://github.com/user-attachments/assets/5e8d20a7-6bd2-45fb-94a2-a8eb7c6d81cd)

截取了一张图片，可以看到文字周围有一圈白色的描边，请问这是什么原因。

**Comment by songxingling1** [comment]
不加描边在特殊的壁纸下（比如我的）会导致文字看不清

**Comment by songxingling1** [comment]
参见#16 qwq

**Comment by songxingling1** [comment]
如果你对你的壁纸有自信的话，可以关闭“文字边框”选项。

**Comment by yiming564** [comment]
试了一下好像还是有 bug：

![image](https://github.com/user-attachments/assets/bc92fee3-a237-43ff-91a0-320808675120)

名字 tag 是属于全局设置的边框的：

```
    // 全局设置边框
    // 除了按钮，输入框光标，分数线，难度选择，加载中动画，专栏查询框，输入框
    *:not(button,.CodeMirror-cursor,.frac-line,.combo-wrapper > .text,.cm-cursor,div[data-v-bbdab89a][style*="border-width: 4px;"],.refined-input,input,h1,hr,blockquote)
        border-color line_color !important
```

**Comment by yiming564** [comment]
@songxingling1
