### ISSUE TITLE
讨论区 bug：跳转到国际版 luogu 时需要手动刷新一下

### ISSUE THREAD

**Issue by yiming564** [Ikaleio/argon-luogu#38]
复现：

1. 打开一道题目的讨论区，例如 [这里](https://www.luogu.com.cn/discuss?forum=P6021)
2. 在当前页面（不要在新标签页打开）该页最后一条：![image](https://github.com/user-attachments/assets/bcc595fe-d797-487d-ab4c-a1a8a625e8af)
3. 本应出现的 `安全访问中心 - 洛谷` 变成了空白页面

如果右键 > 在新标签页打开则正常

**Comment by TLEWA** [comment]
你在这里反馈干啥

**Comment by yiming564** [comment]
那我应该去哪里。。。

**Comment by TLEWA** [comment]
对线洛谷开发组去。

**Comment by yiming564** [comment]
啊不是不是，这个是氩洛谷的 bug

**Comment by yiming564** [comment]
抱歉搞错了，刚刚关了插件测试了一下，确实是洛谷的 bug，~~这就去对线~~

**Comment by songxingling1** [comment]
eee发生了神马
