### ISSUE TITLE
专栏区 bug：编辑文章全屏异常

### ISSUE THREAD

**Issue by yiming564** [Ikaleio/argon-luogu#39]
复现：

1. 在专栏里新建一篇文章，开始编辑
2. 点击右上角全屏
3. ![image](https://github.com/user-attachments/assets/f8b69913-ca5f-4a64-8c02-7f74e92ee0c3)

讨论版的 markdown 编辑器全屏可以正常覆盖全屏，不过洛谷的讨论版也有 bug，bug + bug 了属于是

**Comment by songxingling1** [comment]
fixed.感谢贡献
> ~~其实稍微看一下代码就知道我的解决方式是野蛮.jpg~~

**Comment by yiming564** [comment]
@songxingling1 布什戈门，你只改了深色模式（

~~（而且深色模式的专栏配色也太阴间了，还好我用浅色）~~

**Comment by songxingling1** [comment]
qwq
